# Generated by Django 2.1.5 on 2020-03-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='indicators',
            field=models.CharField(max_length=225),
        ),
    ]
