# Generated by Django 2.1.5 on 2020-03-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='page',
            field=models.CharField(default='landing', max_length=50),
        ),
    ]
