# Generated by Django 2.1.5 on 2020-03-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_indicators_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(choices=[('people', 'PEOPLE'), ('brand', 'BRAND'), ('operation', 'OPERATION'), ('blank', ' ')], default=' ', max_length=100),
        ),
    ]
